/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.forms;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import rs.ac.bg.fon.ps.communication.CommunicationWithServer;
import rs.ac.bg.fon.ps.communication.Operation;
import rs.ac.bg.fon.ps.communication.Request;
import rs.ac.bg.fon.ps.communication.Response;
import rs.ac.bg.fon.ps.domain.Film;
import rs.ac.bg.fon.ps.domain.IDomain;
import rs.ac.bg.fon.ps.helpClasses.PretragaHelp;
import rs.ac.bg.fon.ps.view.tableModels.FilmTableModel;

/**
 *
 * @author GaGiiiii
 */
public class PretraziFilmoveForm extends javax.swing.JDialog {

    private FilmTableModel tableModel;
    private Film selectedFilm;

    public PretraziFilmoveForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Pretrazivanje filmova");
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        naziv = new javax.swing.JTextField();
        pretraziBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        filmoviTable = new javax.swing.JTable();
        movieInfoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cenaInfo = new javax.swing.JLabel();
        reziserInfo = new javax.swing.JLabel();
        opisInfo = new javax.swing.JLabel();
        glumciInfo = new javax.swing.JLabel();
        datumInfo = new javax.swing.JLabel();
        nazivInfo = new javax.swing.JLabel();
        zanrInfo = new javax.swing.JLabel();
        trajanjeInfo = new javax.swing.JLabel();
        obrisiBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("PRETRAZI FILMOVE");

        jLabel3.setText("Unesi naziv");

        pretraziBtn.setText("PRETRAZI");
        pretraziBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pretraziBtnActionPerformed(evt);
            }
        });

        filmoviTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(filmoviTable);

        jLabel2.setText("ZANR:");

        jLabel4.setText("NAZIV:");

        jLabel5.setText("REZISER:");

        jLabel6.setText("OPIS:");

        jLabel7.setText("TRAJANJE:");

        jLabel8.setText("CENA:");

        jLabel9.setText("GLUMCI:");

        jLabel10.setText("DATUM IZLASKA:");

        cenaInfo.setText("jLabel11");

        reziserInfo.setText("jLabel11");

        opisInfo.setText("jLabel11");

        glumciInfo.setText("jLabel11");

        datumInfo.setText("jLabel11");

        nazivInfo.setText("jLabel11");

        zanrInfo.setText("jLabel11");

        trajanjeInfo.setText("jLabel11");

        obrisiBtn.setText("OBRISI");
        obrisiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiBtnActionPerformed(evt);
            }
        });

        closeBtn.setText("ZATVORI");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout movieInfoPanelLayout = new javax.swing.GroupLayout(movieInfoPanel);
        movieInfoPanel.setLayout(movieInfoPanelLayout);
        movieInfoPanelLayout.setHorizontalGroup(
            movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movieInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(movieInfoPanelLayout.createSequentialGroup()
                        .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cenaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(movieInfoPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(trajanjeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(movieInfoPanelLayout.createSequentialGroup()
                                    .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2))
                                    .addGap(67, 67, 67)
                                    .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(zanrInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nazivInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(movieInfoPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(reziserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(movieInfoPanelLayout.createSequentialGroup()
                                .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opisInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(glumciInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datumInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(movieInfoPanelLayout.createSequentialGroup()
                                .addComponent(obrisiBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(closeBtn)))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(movieInfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        movieInfoPanelLayout.setVerticalGroup(
            movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movieInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nazivInfo))
                .addGap(18, 18, 18)
                .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zanrInfo)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(trajanjeInfo))
                .addGap(18, 18, 18)
                .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cenaInfo))
                .addGap(18, 18, 18)
                .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(reziserInfo))
                .addGap(18, 18, 18)
                .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(datumInfo))
                .addGap(18, 18, 18)
                .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(glumciInfo)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opisInfo)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(movieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obrisiBtn)
                    .addComponent(closeBtn))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movieInfoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(naziv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pretraziBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(naziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pretraziBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(movieInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pretraziBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pretraziBtnActionPerformed
        try {

            String nazivf = naziv.getText();
            LinkedList<IDomain> filmovi = new LinkedList<>();

            Request req = new Request();
            req.setOperation(Operation.PRETRAZI_FILMOVE);
            req.setParameter(new PretragaHelp(nazivf, filmovi));

            CommunicationWithServer.getInstance().sendRequest(req);
            Response res = CommunicationWithServer.getInstance().getResponse();

            if (res.getException() == null) {
                tableModel = new FilmTableModel((List<Film>) res.getResponse());
                filmoviTable.setModel(tableModel);
            } else {
                JOptionPane.showMessageDialog(this, res.getException().getMessage(), "Neuspesno pretrazivanje filmova", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom pretrazivanja", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_pretraziBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        movieInfoPanel.setVisible(false);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void obrisiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiBtnActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Da li ste sigurni da zelite da obrisete film \n\"" + selectedFilm.getNaziv() + "\"?", "UPOZORENJE!", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try {
                Request req = new Request();
                req.setOperation(Operation.OBRISI_FILM);
                req.setParameter(selectedFilm);

                CommunicationWithServer.getInstance().sendRequest(req);
                Response res = CommunicationWithServer.getInstance().getResponse();

                if (res.getException() == null) {
                    JOptionPane.showMessageDialog(this, "Sistem je obrisao film", "Uspesno obrisan film", JOptionPane.INFORMATION_MESSAGE);
                    req.setOperation(Operation.UCITAJ_LISTU_FILMOVA);

                    CommunicationWithServer.getInstance().sendRequest(req);
                    res = CommunicationWithServer.getInstance().getResponse();
                    LinkedList<Film> filmovi = (LinkedList<Film>) res.getResponse();
                    tableModel = new FilmTableModel((List<Film>) res.getResponse());
                    filmoviTable.setModel(tableModel);
                    selectedFilm = null;
                    movieInfoPanel.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, res.getException().getMessage(), "Neuspesno brisanje filma", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom brisanja filma", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_obrisiBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cenaInfo;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel datumInfo;
    private javax.swing.JTable filmoviTable;
    private javax.swing.JLabel glumciInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel movieInfoPanel;
    private javax.swing.JTextField naziv;
    private javax.swing.JLabel nazivInfo;
    private javax.swing.JButton obrisiBtn;
    private javax.swing.JLabel opisInfo;
    private javax.swing.JButton pretraziBtn;
    private javax.swing.JLabel reziserInfo;
    private javax.swing.JLabel trajanjeInfo;
    private javax.swing.JLabel zanrInfo;
    // End of variables declaration//GEN-END:variables

    private void init() {
        obrisiBtn.setEnabled(false);
        try {
            movieInfoPanel.setVisible(false);

            Request req = new Request();
            req.setOperation(Operation.UCITAJ_LISTU_FILMOVA);

            CommunicationWithServer.getInstance().sendRequest(req);
            Response res = CommunicationWithServer.getInstance().getResponse();
            LinkedList<Film> filmovi = (LinkedList<Film>) res.getResponse();

            tableModel = new FilmTableModel(filmovi);
            filmoviTable.setModel(tableModel);
        } catch (Exception e) {
            e.printStackTrace();
        }

        filmoviTable.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent mouseEvent) {
                JTable table = (JTable) mouseEvent.getSource();
                Point point = mouseEvent.getPoint();
                int row = table.rowAtPoint(point);
                if (mouseEvent.getClickCount() == 2 && table.getSelectedRow() != -1) {
                    obrisiBtn.setEnabled(true);
                    Film film = (Film) tableModel.getValueAtRow(row);
                    selectedFilm = film;
                    movieInfoPanel.setVisible(true);
                    nazivInfo.setText(film.getNaziv());
                    zanrInfo.setText(film.getZanr());
                    trajanjeInfo.setText(film.getTrajanje() + " min");
                    cenaInfo.setText(film.getCena_karte() + " RSD");
                    reziserInfo.setText(film.getReziser());
                    glumciInfo.setText(film.getGlumci());
                    datumInfo.setText(film.getDatum_izlaska() + "");
                    opisInfo.setText(film.getOpis());
                }
            }
        });
    }

}
